### PR TITLE
Typos in documentation

### PR DESCRIPTION
**Pull request by futreall**
Fixed typos and standardized terminology across key documentation sections for clarity and professionalism.

1. **infrasturcture** → **infrastructure**
2. **Miscelaneous deployments** → **Miscellaneous deployments**
3. **alltogether** → **altogether**
4. **Merged minig** → **Merged mining**
5. **PLan** → **Plan**
6. **dencentralized** → **decentralized**
7. **decentalized appliocations** → **decentralized applications**
8. **epxressive** → **expressive**
9. **Briding** → **Bridging**

### CODE REVIEW

**Comment by futreall** [comment]
Hey! Thanks for the approval 🙌. Could you please run the migration to apply the changes? I’d really appreciate it!

**Comment by derrekcoleman** [comment]
Call me old-fashioned, but auto-generated PRs nit-picking typos in a folder called drafts with pages that aren't published so the author can be listed as a contributor to an open-source repo rubs me the wrong way.

**Comment by futreall** [comment]
😁😁😁

**Comment by futreall** [comment]
> 😁😁😁 , all good , thanks !

**Pull request closed without merging**
