### PR TITLE
docs: Update hello bitcoin guide

### LINKED ISSUE #159: Publishing & verifying smart contracts fails through remix if remappings present
**Describe the bug**
Based on the [hello bitcoin guide](https://docs.gobob.xyz/docs/build/getting-started/helloworld#extra-publish-and-verify-the-hellobitcoin-contract). Remix is not flattening smart contract as expected if the smart contract has remappings. 

- [Tracking issue](https://github.com/ethereum/remix-project/issues/4510) on remix project repo. 
**- Issue fixed in remix, v0.43.0 released.**

### PR DESCRIPTION
**Pull request by nakul1010**
The Pr does the following. 
- Closes #159. 
- display `foundry` tab as primary, reasons
    - `starterkit` in foundry.  
    - all of bob repos developed with foundry. 
- Create separate remix and foundry tabs for verifying smart contract

### CODE REVIEW

**Comment by nud3l** [comment]
Why do we need to comment our docs for remix?

**Comment by nud3l** [comment]
Did you maybe want to comment out the comments in the Solidity follow?

**Comment by nakul1010** [comment]
> Did you maybe want to comment out the comments in the Solidity follow?

I want to comment out `Extra: Publish and verify the HelloBitcoin Contract` section since it's not working as expected. It not generating the `HelloBitcoin` flattened code required to publish.

**Comment by nud3l** [comment]
In that case, then only comment it out for the remix part since it should work for the forge deployment, right?

**Comment by nakul1010** [comment]
> In that case, then only comment it out for the remix part since it should work for the forge deployment, right?

The steps are specifically for remix only, for forge, we are verifying during deployment itself  check the following command in the guide
`forge script script/HelloBitcoin.sol --rpc-url=$RPC_URL --broadcast --verify --verifier blockscout --verifier-url=$VERIFIER_URL
`

**Pull request merged**
